### PR TITLE
upload assignment 6

### PR DESCRIPTION
**Pull request by gdevanna**
i've just uploaded assignment 6

### CODE REVIEW

**Comment by bnajafi** [comment]
there is a hidden file called: .DS_Store which is made by mac operating system, please remove it using:
rm command and pull another request

**Comment by gdevanna** [comment]
i see the file on my Git Hub folder but i cannot remove it.
Have i to operato by the bash??
Guglielmo De Vanna

2017-10-30 22:11 GMT+01:00 Behzad Najafi <notifications@github.com>:

**Comment by gdevanna** [comment]
I think that i removed the file successfully.
i used the command "rm –f .DS_STore" in almost every folder. There was one of that file in almost every file that i've uploaded in the past. 
Unfortunately i cannot remove the one located in my first folder on GIT! i really don't know what to do! could we try togheter on Thursday? 
Best Reagards 
Guglielmo De Vanna

**Comment by gdevanna** [comment]
i've just uploaded file 7

**Pull request closed without merging**
